////////////////////////////////////////////////////////////////////////
// Class:       RawDigitAna
// Module Type: analyzer
// File:        RawDigitAna_module.cc
//
// Generated at Tue Nov 10 13:06:09 2015 by Wesley Ketchum using artmod
// from cetpkgsupport v1_08_07.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "art/Framework/Services/Optional/TFileService.h"

#include "TTree.h"

#include "RawDigitAnaAlg/RawDigitAnaAlg.hh"

namespace tpc {
  class RawDigitAna;
}

class tpc::RawDigitAna : public art::EDAnalyzer {
public:
  explicit RawDigitAna(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  RawDigitAna(RawDigitAna const &) = delete;
  RawDigitAna(RawDigitAna &&) = delete;
  RawDigitAna & operator = (RawDigitAna const &) = delete;
  RawDigitAna & operator = (RawDigitAna &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void reconfigure(fhicl::ParameterSet const & p) override;

private:

  // Declare member data here.
  tpc::RawDigitAnaAlg fMyAnalysisObj;
  
};


tpc::RawDigitAna::RawDigitAna(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{
  art::ServiceHandle<art::TFileService> tfs;
  fMyAnalysisObj.SetupOutputTree(tfs->make<TTree>("myanatree","MyAnalysis Tree"));
}

void tpc::RawDigitAna::analyze(art::Event const & e)
{
  art::Handle<std::vector<raw::RawDigit> > waveformHandle;
  e.getByLabel("daq",waveformHandle);
  if(!waveformHandle.isValid()) throw std::exception();
  std::vector<raw::RawDigit> const& waveformVector(*waveformHandle);

  fMyAnalysisObj.RunAnalysis(waveformVector);
}

void tpc::RawDigitAna::reconfigure(fhicl::ParameterSet const & p)
{
  // Implementation of optional member function here.
}

DEFINE_ART_MODULE(tpc::RawDigitAna)
